# Generated by Django 3.0.8 on 2021-08-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('num_documento', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('referencia_nombre', models.CharField(max_length=50)),
                ('referencia_celular', models.CharField(max_length=10)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.TipoDocumento')),
            ],
        ),
    ]
