# Generated by Django 3.0.8 on 2021-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='icono',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
